### ISSUE TITLE
&debug overwrites metadata options

### ISSUE THREAD

**Issue by zeroclutch** [zeroclutch/gamebot#9]
**Describe the bug**
https://github.com/zeroclutch/gamebot/blob/eb3abf117200d1dd902d0877fe2a23ccb2ca486d/commands/dev/debug.js#L37
This line overwrites the stored game metadata instead of the game instance.

**To Reproduce**
1. Run a game using &debug id.
2. Run the same game using &play and with fewer players than typically allowed.
3. The game will start anyway.

**Expected behavior**
There should be an error message saying that not enough players joined the game, terminating the game immediately.

**Desktop (please complete the following information):**
macOS 11.0.1, standard Discord build.

**Comment by ConnorDoesDev** [comment]
was this ever fixed..? if not, i'll go ahead and try to make a pr for that.

**Comment by zeroclutch** [comment]
@ConnorDoesDev Good question, I think this actually works as intended, so that games can run with 0 users for testing purposes. Since this is a dev command, there's really no use in "fixing" this.

**Comment by ConnorDoesDev** [comment]
👍 that makes sense
